//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingCartMVC.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbOnlineStoreEntities1 : DbContext
    {
        public dbOnlineStoreEntities1()
            : base("name=dbOnlineStoreEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tblCategory> tblCategories { get; set; }
        public DbSet<tblInvoice> tblInvoices { get; set; }
        public DbSet<tblOrder> tblOrders { get; set; }
        public DbSet<tblProduct> tblProducts { get; set; }
        public DbSet<tblUser> tblUsers { get; set; }
        public DbSet<vw_getallproducts> vw_getallproducts { get; set; }
        public DbSet<viewallproduct> viewallproducts { get; set; }
        public DbSet<getallorder> getallorders { get; set; }
        public DbSet<getallorderuser> getallorderusers { get; set; }
        public DbSet<user_invoices> user_invoices { get; set; }
    }
}
