//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShoppingCartMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblOrder
    {
        public int OrderId { get; set; }
        public Nullable<int> ProID { get; set; }
        public string Contact { get; set; }
        public string Address { get; set; }
        public Nullable<int> Unit { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<int> Total { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public Nullable<int> InvoiceId { get; set; }
    
        public virtual tblInvoice tblInvoice { get; set; }
        public virtual tblProduct tblProduct { get; set; }
    }
}
